return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = { "windwp/nvim-ts-autotag", "JoosepAlviste/nvim-ts-context-commentstring" },
  cmd = {
    "TSBufDisable",
    "TSBufEnable",
    "TSBufToggle",
    "TSDisable",
    "TSEnable",
    "TSToggle",
    "TSInstall",
    "TSInstallInfo",
    "TSInstallSync",
    "TSModuleInfo",
    "TSUninstall",
    "TSUpdate",
    "TSUpdateSync",
  },
  build = ":TSUpdate",
  opts = {
    highlight = { enable = true },
    incremental_selection = { enable = true },
    indent = { enable = true },
    autotag = {
      enable = true,
      enable_rename = true,
    },
    context_commentstring = { enable = true, enable_autocmd = false },
    ensure_installed = {
      "markdown",
      "markdown_inline",
      "tsx",
      "typescript",
      "rust",
      "toml",
      "fish",
      "php",
      "json",
      "yaml",
      "rust",
      "python",
      "css",
      "html",
      "lua",
    },
  },
  config = require("plugins.configs.nvim-treesitter"),
}
