return {}
--return {
--	"L3MON4D3/LuaSnip",
--	lazy = false,
--  event  = "VeryLazy",
--	build = "make install_jsregexp",
--	config = function()
--		require("luasnip.loaders.from_vscode").load()
--		--require("luasnip.loaders.from_vscode").load({ paths = {"./my_snippets"} })
--		--require("luasnip.loaders.from_lua").load({ paths = "./my_snippets" })
--	end,
--	dependencies = { { "rafamadriz/friendly-snippets", event = "LspAttach" } },
--}
