require("lucas.options")
require("lucas.globals")
require("lucas.packages")
require("lucas.mason")
require("lucas.keymaps")
require("lucas.filetypes")
require("lucas.knap")
require("lucas.dap_config")
require("lucas.colorscheme")
require("lucas.autocmds")

