require("lucas.options")
require("lucas.globals")
require("lucas.packages")
require("lucas.mason")
require("lucas.keymaps")
require("lucas.colorscheme")
require("lucas.autocmds")
require("lucas.commands")
require("lucas.snippets")

